import assert from "node:assert/strict";
import test from "node:test";
import { runnerImport } from "vite";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { makeWorkflowDashboard } from "./fixtures/monthly-workflow.mjs";
const options = { configFile: false, envDir: false };
test("closing distinguishes missing, inactive, empty, pending and closed months", async () => {
  const { module: c } = await runnerImport("./app/closing-model.ts", options);
  const data = makeWorkflowDashboard(), before = structuredClone(data);
  let rows = c.buildClosingRows(data);
  assert.equal(rows.find(row => row.contractorId === "person-1").status, "READY");
  assert.equal(rows.find(row => row.contractorId === "person-2").status, "READY");
  assert.equal(rows.find(row => row.contractorId === "person-3").status, "NO_RECORD");
  assert.deepEqual(data, before);
  data.entries[0].nonBusinessDayStatus = "PENDING_AUTHORIZATION";
  assert.equal(c.buildClosingRows(data)[0].status, "PENDING");
  data.entries = data.entries.filter(entry => entry.contractorId !== "person-1");
  assert.equal(c.buildClosingRows(data)[0].status, "NO_ENTRIES");
  data.monthlyTimesheets[0].status = "CLOSED";
  assert.equal(c.buildClosingRows(data)[0].status, "CLOSED");
  delete data.monthlyTimesheets;
  assert.equal(c.buildClosingRows(data)[0].status, "UNKNOWN");
  data.period.to = "2026-09-01";
  assert.throws(() => c.buildClosingRows(data));
});
test("review accepts explicit ready targets but never invents missing or empty months", async () => {
  const { module: c } = await runnerImport("./app/closing-model.ts", options);
  const data = makeWorkflowDashboard();
  let rows = c.buildClosingRows(data);
  assert.deepEqual(c.makeClosingCommand(data.period, rows, ["person-1"], []), { year: 2026, month: 8, contractorIds: ["person-1"] });
  assert.throws(() => c.makeClosingCommand(data.period, rows, ["person-3"], []));
  assert.throws(() => c.makeClosingCommand(data.period, rows, [], []));
  data.entries = data.entries.filter(entry => entry.contractorId !== "person-1");
  rows = c.buildClosingRows(data);
  assert.throws(() => c.makeClosingCommand(data.period, rows, ["person-1"], []));
  assert.equal(c.makeClosingCommand(data.period, rows, ["person-1"], ["person-1"]).contractorIds.length, 1);
});
test("closing issues retain person and day and avoid duplicate authorization issues", async () => {
  const { module: c } = await runnerImport("./app/closing-model.ts", options);
  const data = makeWorkflowDashboard();
  data.entries[0].nonBusinessDayStatus = "PENDING_AUTHORIZATION";
  data.authorizations = [{ id: "auth-1", contractorId: "person-1", contractorName: "Ana Exemplo", workDate: "2026-08-03", estimatedMinutes: 480, approvedMinutes: null, reason: "Teste", status: "REQUESTED", requestedAt: "2026-08-02T12:00:00Z", decisionNotes: "" }];
  const issues = c.buildClosingRows(data).find(row => row.contractorId === "person-1").issues;
  assert.equal(issues.length, 1);
  assert.equal(issues[0].sourceId, "auth-1");
  assert.equal(issues[0].workDate, "2026-08-03");
  assert.equal(issues[0].contractorId, "person-1");
});
test("partial, duplicate and malformed results cannot claim team success", async () => {
  const { module: c } = await runnerImport("./app/closing-model.ts", options);
  const command = { year: 2026, month: 8, contractorIds: ["person-1", "person-2"] };
  const one = { contractorId: "person-1", status: "closed" };
  let result = c.normalizeClosingResults(command, [one]);
  assert.equal(result.complete, false);
  assert.equal(result.results[1].status, "uncertain");
  result = c.normalizeClosingResults(command, [one, one]);
  assert.equal(result.results[0].status, "uncertain");
  assert.equal(c.normalizeClosingResults(command, null).complete, false);
  assert.equal(c.normalizeClosingResults(command, [null]).complete, false);
  assert.equal(c.normalizeClosingResults(command, [{ ...one, message: { invalid: true } }]).results[0].status, "uncertain");
  assert.equal(c.normalizeClosingResults(command, [one, { contractorId: "person-2", status: "already-closed" }]).complete, true);
  assert.equal(c.normalizeClosingResults(command, [one, { contractorId: "person-2", status: "closed" }, { contractorId: "stranger", status: "closed" }]).complete, false);
});
test("real confirmation stays unavailable when no validated operation is provided", async () => {
  const { module: v } = await runnerImport("./app/ClosingConfirmation.tsx", options);
  const html = renderToStaticMarkup(createElement(v.ClosingConfirmation, { command: { year: 2026, month: 8, contractorIds: ["person-1"] }, rows: [], onClose() {}, onSettled() {} }));
  assert.match(html, /Fechamento real ainda indisponível/);
  assert.match(html, /disabled=""[^>]*>Fechar mês da equipe/);
});
